#networks:
#  postgres:
#    driver: bridge

services:
  postgres:
    container_name: "postgres"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
#    networks:
#      - postgres

  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5430:80"
    depends_on:
      - postgres
#    networks:
#      - postgres
